WebMvcUI/Areas/Admin/Controllers/BedTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebMvcUI.Areas.Admin.Controllers
{
    [Authorize(Roles = Constants.ROLE_ADMINISTRATORS)]
    [Area("admin")]
    public class BedTypesController : Controller
    {
        private readonly IRoomService _roomService;
        private readonly UserManager<ApplicationUser> _userManager;

        public BedTypesController(IRoomService roomService, UserManager<ApplicationUser> userManager)
        {
            _roomService = roomService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "BedType Listing";

            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "BedType Listing";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "dashboard", ActionName = "index", AreaName = "admin", IsActive = false, Title = "Dashboard" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "BedType Listing", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            var bedtypes = await _roomService.GetBedTypes();

            return View(GetViewModels(bedtypes));
        }

        public IActionResult Create()
        {
            ViewBag.Title = "BedType Create";

            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Create BedType";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "bedtypes", ActionName = "index", AreaName = "admin", IsActive = false, Title = "BedType Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Create BedType", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BedTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                var bedType = new BedType()
                {
                    BedTypeName = model.BedTypeName,
                    CreatedBy = user != null ? user.UserName : string.Empty
                };

                await _roomService.AddBedType(bedType);

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            ViewBag.Title = "BedType Update";

            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Update BedType";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "bedtypes", ActionName = "index", AreaName = "admin", IsActive = false, Title = "BedType Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Update BedType", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            if (id == null)
            {
                return NotFound();
            }

            var bedType = await _roomService.GetBedTypeByIdAsync(id);

            if (bedType == null)
            {
                return NotFound();
            }

            return View(BindViewModel(bedType));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, BedTypeViewModel model)
        {
            if (id != model.BedTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var bedTypeUpdate = await _roomService.GetBedTypeByIdAsync(model.BedTypeId);

                if (bedTypeUpdate != null)
                {
                    var user = await _userManager.GetUserAsync(User);

                    bedTypeUpdate.LastModifiedBy = user != null ? user.UserName : string.Empty;
                    bedTypeUpdate.LastModifiedDate = DateTime.Now;
                    bedTypeUpdate.BedTypeName = model.BedTypeName;

                    await _roomService.UpdateBedType(bedTypeUpdate);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            ViewBag.Title = "BedType Delete";
            
            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Delete BedType";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "bedtypes", ActionName = "index", AreaName = "admin", IsActive = false, Title = "BedType Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Delete BedType", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            if (id == null)
            {
                return NotFound();
            }


            var bedType = await _roomService.GetBedTypeByIdAsync(id);

            if (bedType == null)
            {
                return NotFound();
            }

            return View(BindViewModel(bedType));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            await _roomService.DeleteBedType(id);

            return RedirectToAction(nameof(Index));
        }

        private IEnumerable<BedTypeViewModel> GetViewModels(IEnumerable<BedType> bedTypes)
        {
            return bedTypes.Select(x => BindViewModel(x));
        }

        private BedTypeViewModel BindViewModel(BedType bedType)
        {
            return new BedTypeViewModel()
            {
                BedTypeId = bedType.BedTypeId,
                BedTypeName = bedType.BedTypeName,
                CreatedBy = bedType.CreatedBy,
                CreatedDate = bedType.CreatedDate,
                LastModifiedBy = bedType.LastModifiedBy,
                LastModifiedDate = bedType.LastModifiedDate,
            };
        }
    }
}

WebMvcUI/Areas/Admin/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebMvcUI.Areas.Admin.Controllers
{
    [Authorize(Roles = Constants.ROLE_ADMINISTRATORS)]
    [Area("admin")]
    public class CitiesController : Controller
    {

        private readonly ILocationService _locationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public CitiesController(ILocationService locationService, UserManager<ApplicationUser> userManager)
        {
            _locationService = locationService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var cities = await _locationService.GetCities();

            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "City Listing";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "dashboard", ActionName = "index", AreaName = "admin", IsActive = false, Title = "Dashboard" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "City Listing", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;


            return View(
                cities.Select(x => new CityViewModel
                {
                    Id = x.CityId,
                    CityName = x.CityName,
                    CreatedDate = x.CreatedDate,
                    CreatedBy = x.CreatedBy,
                    LastModifiedDate = x.LastModifiedDate,
                    LastModifiedBy = x.LastModifiedBy
                })
                );
        }

        public IActionResult Create()
        {
            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Create City";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "cities", ActionName = "index", AreaName = "admin", IsActive = false, Title = "City Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Create City", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CityViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);

                City city = new City()
                {
                    CityName = model.CityName,
                    CreatedBy = user != null ? user.UserName : string.Empty,
                };

                await _locationService.AddCity(city);

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Update City";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "cities", ActionName = "index", AreaName = "admin", IsActive = false, Title = "City Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Update City", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            if (id == null)
            {
                return NotFound();
            }

            City city = await _locationService.GetCityById(id);

            if (city == null)
            {
                return NotFound();
            }
            return View(new CityViewModel { Id = city.CityId, CityName = city.CityName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, CityViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var updateCity = await _locationService.GetCityById(id);

                if (updateCity != null)
                {
                    var user = await _userManager.GetUserAsync(User);

                    updateCity.CityName = model.CityName;
                    updateCity.LastModifiedBy = user != null ? user.UserName : string.Empty;
                    updateCity.LastModifiedDate = DateTime.Now;

                    await _locationService.UpdateCity(updateCity);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            ContentHeaderViewModel contentHeader = new ContentHeaderViewModel();
            contentHeader.Title = "Delete City";
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { ControllerName = "cities", ActionName = "index", AreaName = "admin", IsActive = false, Title = "City Listing" });
            contentHeader.Breadcrumbs.Add(new BreadcrumbViewModel { Title = "Delete City", IsActive = true });

            ViewData["ContentHeader"] = contentHeader;

            if (id == null)
            {
                return NotFound();
            }
            var city = await _locationService.GetCityById(id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                await _locationService.DeleteCity(id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMvcUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] [Panda Hotel Booking] </title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/lib/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/lib/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/lib/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/lib/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css">

      <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/datatables-buttons/css/buttons.bootstrap4.min.css">

     <link rel="stylesheet" href="~/lib/dropzone/min/dropzone.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/jdatagrid/css/jgrid.css" rel="stylesheet" asp-append-version="true" />
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/lib/AdminLTE-3.2.0/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <span class="nav-link d-flex align-items-center">
                            <i class="fas fa-user-circle"></i> <span class="mr-3">@UserManager.GetUserName(User) </span>
                            <a asp-controller="Account" asp-action="Logout" asp-area="Admin" class="text-secondary">
                                <i class="fas fa-sign-out-alt"></i>
                                Logout
                            </a>
                        </span>
                    </li>
                }
                

                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <img src="~/lib/AdminLTE-3.2.0/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">PANDA HOTEL</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">

                <!-- SidebarSearch Form -->
                <div class="form-inline mt-3">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tools"></i>
                                <p>
                                    Master Data Setup
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="Cities" asp-action="Index">
                                        <i class="nav-icon fas fa-building"></i>
                                        <p>City</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="Townships" asp-action="Index"><i class="nav-icon fas fa-location-arrow"></i> <p>Township</p></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="RoomTypes" asp-action="Index"><i class="nav-icon fas fa-key"></i> <p>Room Type</p></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="BedTypes" asp-action="Index"><i class="nav-icon fas fa-bed"></i> <p>Bed Type</p></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="FacilityTypes" asp-action="Index"><i class="nav-icon fas fa-wifi"></i> <p>Facility Type</p></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="Cities" asp-action="Index"><i class="nav-icon fas fa-users"></i> <p>Users</p></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="admin" asp-controller="Cities" asp-action="Index"><i class="nav-icon fas fa-user-tag"></i> <p>Roles</p></a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-header">HOTEL MANAGEMENT</li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="admin" asp-controller="hotels" asp-action="Index"><i class="nav-icon fas fa-hotel"></i> <p>Hotels</p></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="admin" asp-controller="rooms" asp-action="Index"><i class="nav-icon fas fa-door-open"></i> <p>Rooms</p></a>
                        </li>
                        <li class="nav-header">BOOKING MANAGEMENT</li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="admin" asp-controller="bookings" asp-action="Index"><i class="nav-icon fas fa-bell"></i> <p>Booking</p></a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <partial name="_ContentHeader" />

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021  Panda Hotel</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/lib/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/lib/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/lib/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/lib/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/lib/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/lib/moment/moment.min.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/lib/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/lib/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/AdminLTE-3.2.0/js/adminlte.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/lib/jszip/jszip.min.js"></script>
    <script src="~/lib/pdfmake/pdfmake.min.js"></script>
    <script src="~/lib/pdfmake/vfs_fonts.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/lib/datatables-buttons/js/buttons.colVis.min.js"></script>

    <!-- dropzonejs -->
    <script src="~/lib/dropzone/min/dropzone.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jdatagrid/js/jdatagrid.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

WebMvcUI/Views/Shared/_UserLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
    </li>
    <li class="nav-item">
        <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}
</ul>